name: Beta CI

on:
  pull_request:
    branches-ignore:
      - "main"

jobs:
  release-please:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
          check-version: true
          tag: prerelease
