name: Beta CI

on:
  push:
    branches:
      - beta

jobs:
  release-please:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm versioning
        id: npmVersioning
        uses: pengyanb/npm-versioning-action@v1

      - name: dummy versioning usage
        run: echo "Generated version is \${{ steps.npmVersioning.outputs.version}}"

      # - name: Install Dependencies
      #   if: ${{ steps.release.outputs.release_created }}
      #   run: yarn

      # - uses: JS-DevTools/npm-publish@v1
      #   if: ${{ steps.release.outputs.release_created }}
      #   with:
      #     registry: https://npm.pkg.github.com
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     dry-run: true
