name: Main CI

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: "@jacob-ebey/library-boilerplate"

      - uses: JS-DevTools/npm-publish@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
          check-version: true

      - uses: JS-DevTools/npm-publish@v1
        if: ${{ !steps.release.outputs.release_created }}
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
          check-version: true
          tag: prerelease
