name: Main CI

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: "@jacob-ebey/library-boilerplate"

      - uses: JS-DevTools/npm-publish@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
          check-version: true

      - name: get-npm-version
        if: ${{ !steps.release.outputs.release_created }}
        id: version
        uses: martinbeentjes/npm-get-version-action@master

      - uses: JS-DevTools/npm-publish@v1
        if: ${{ !steps.release.outputs.release_created }}
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
          check-version: true
          tag: ${{ steps.version.outputs.current-version }}
